language: go
go:
  - tip
before_script:
  - if [ "${TRAVIS_BRANCH}" = "gobranch" ]; then source ./ready_go.sh;fi
  - echo ${TRAVIS_BRANCH}
script:
  - if [ "${TRAVIS_BRANCH}" = "gobranch" ]; then source ./test_go.sh;fi